// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/ClipboardFormats.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.desktop
{

    public class ClipboardFormats
    {
        // Image data (AIR only).
        [API("661")]
        public static const BITMAP_FORMAT:String = "air:bitmap";
        
        // An array of files (AIR only).
        [API("661")]
        public static const FILE_LIST_FORMAT:String = "air:file list";

        //  File promise list (AIR only).
        [API("668")]
        public static const FILE_PROMISE_LIST_FORMAT:String = "air:file promise list";

        // HTML data.
        public static const HTML_FORMAT:String = "air:html";

        // Rich Text Format data.
        public static const RICH_TEXT_FORMAT:String = "air:rtf";

        // String data.
        public static const TEXT_FORMAT:String = "air:text";

        // A URL string (AIR only). 
        [API("661")]
        public static const URL_FORMAT:String = "air:url"

    }
}
