// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/events/HTMLUncaughtScriptExceptionEvent.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.events
{

  public class HTMLUncaughtScriptExceptionEvent extends Event
  {

    // The result of evaluating the expression in the throw statement that resulted in the uncaught exception.
    public var exceptionValue:*;

    // An array of objects that represent the stack trace at the time the throw statement that resulted in the uncaught exception was executed.
    public var stackTrace:Array;

    public function HTMLUncaughtScriptExceptionEvent(exceptionValue:*)
    {

    }

    // [override] Creates a copy of the HTMLUncaughtScriptExceptionEvent object and sets the value of each property to match that of the original.
    override public function clone():Event
    {
      return new HTMLUncaughtScriptExceptionEvent(this.type, this.bubbles, this.cancelable);
    }
  }
}
