// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/html/HTMLHost.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.html
{
    
    import flash.geom.Rectangle;
    import flash.html.HTMLLoader;
    
    
    public class HTMLHost
    {
        

        // The HTMLLoader object to which this HostControl object applies.
        private var _htmlLoader: HTMLLoader;
        
        // The property that is changed when JavaScript code in the HTMLLoader object calls the window.moveBy(), window.moveTo(), window.resizeBy(), or window.resizeTo() method.
        public var windowRect: Rectangle;
        

        
        public function HTMLHost(defaultBehaviors:Boolean = true)
        {
            
        }
        
        
        

        // The function called when JavaScript code in the HTMLLoader object calls the window.open() method.
        public function createWindow(windowCreateOptions:HTMLWindowCreateOptions):HTMLLoader
        {
            // Unknown Implementation
            return new HTMLLoader
        }

        // The function called when JavaScript code in the HTMLLoader object sets the window.location property.
        public function updateLocation(locationURL:String):void
        {
            // Unknown Implementation
        }

        // The function called when JavaScript code in the HTMLLoader object sets the window.status property.
        public function updateStatus(status:String):void
        {
            // Unknown Implementation
        }

        // The function called when JavaScript code in the HTMLLoader object sets the window.document.title property or when the title element changes, either via the DOM or because of a new page load.
        public function updateTitle(title:String):void
        {
            // Unknown Implementation
        }

        // The function called when JavaScript code in the HTMLLoader object calls the window.blur() method.
        public function windowBlur():void
        {
            // Unknown Implementation
        }

        // The function called when JavaScript code in the HTMLLoader object calls the window.close() method.
        public function windowClose():void
        {
            // Unknown Implementation
        }

        // The function called when JavaScript code in the HTMLLoader object calls the window.focus() method.
        public function windowFocus():void
        {
            // Unknown Implementation
        }

        public function get htmlLoader() : HTMLLoader
        {
            return this._htmlLoader;
        }
        
    }
}
