// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/html/HTMLHistoryItem.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.html
{
    
    
    public class HTMLHistoryItem
    {
        

        // Indicates whether the HTML page includes POST data.
        private var _isPost: Boolean;
        
        // The original URL of the HTML page, before any redirects.
        private var _originalUrl: String;
        
        // The title of the HTML page.
        private var _title: String;
        
        // The URL of the HTML page.
        private var _url: String;
        

        
        
        

        public function get isPost() : Boolean
        {
            return this._isPost;
        }
        

        public function get originalUrl() : String
        {
            return this._originalUrl;
        }
        

        public function get title() : String
        {
            return this._title;
        }
        

        public function get url() : String
        {
            return this._url;
        }
        
    }
}
