// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/html/HTMLSWFCapability.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.html
{
    
    
    public final class HTMLSWFCapability
    {
        // No version of Adobe Flash Player is detected.
        public static const ERROR_INSTALLED_PLAYER_NOT_FOUND:int = 3221;
        
        // Adobe Flash Player is detected, but the version is too old.
        public static const ERROR_INSTALLED_PLAYER_TOO_OLD:int = 3222;
        
        // A sufficient version of Adobe Flash Player is detected and SWF content can be loaded in a HTMLLoader object.
        public static const STATUS_OK:int = 0;
        
        
    }
}
