// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/html/HTMLPDFCapability.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.html
{
    
    
    public final class HTMLPDFCapability
    {
        // An error was returned by the OS when trying to load the Adobe Reader or Acrobat application or one of its necessary libraries.
        public static const ERROR_CANNOT_LOAD_READER:int = 3204;
        
        // No version of Adobe Reader is detected.
        public static const ERROR_INSTALLED_READER_NOT_FOUND:int = 3201;
        
        // Adobe Reader is detected, but the version is too old.
        public static const ERROR_INSTALLED_READER_TOO_OLD:int = 3202;
        
        // A sufficient version (8.1 or later) of Adobe Reader or Acrobat is detected, but the the version of Adobe Reader that is set up to handle PDF content is older than Adobe Reader or Acrobat 8.1.
        public static const ERROR_PREFERRED_READER_TOO_OLD:int = 3203;
        
        
    }
}
