// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/FileStream.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.filesystem
{
  import __ruffle__.stub_method;
  import __ruffle__.stub_getter;
  import __ruffle__.stub_constructor;
  import flash.events.EventDispatcher;
  import flash.utils.ByteArray;

  [Ruffle(InstanceAllocator)]
  [API("661")]
  public class FileStream extends EventDispatcher
  {
    public var endian:String = "LITTLE_ENDIAN";
    // public var readAhead:Number;

    public function FileStream()
    {
    }

    public native function get objectEncoding():uint;
    public native function set objectEncoding(version:uint):void;

    public native function close():void;
    public native function open(file:File, fileMode:String):void;

    // Opens the FileStream object asynchronously, pointing to the file specified by the file parameter.
    public function openAsync(file:File, fileMode:String):void
    {
      // Unknown Implementation
      stub_method("flash.filesystem.FileStream", "openAsync");
    }

    public native function truncate():void;

    public native function readBoolean():Boolean;
    public native function readByte():int;
    public native function readBytes(bytes:ByteArray, offset:uint = 0, length:uint = 0):void;
    public native function readDouble():Number;
    public native function readFloat():Number;
    public native function readInt():int;
    public native function readMultiByte(length:uint, charSet:String):String;
    public native function readShort():int;
    public native function readUnsignedByte():uint;
    public native function readUnsignedInt():uint;
    public native function readUnsignedShort():uint;
    public native function readUTF():String;
    public native function readUTFBytes(length:uint):String;
    public native function readObject():*;

    public native function writeBoolean(value:Boolean):void;
    public native function writeByte(value:int):void;
    public native function writeDouble(value:Number):void;
    public native function writeFloat(value:Number):void;
    public native function writeInt(value:int):void;
    public native function writeShort(value:int):void;
    public native function writeUnsignedInt(value:uint):void;
    public native function writeObject(object:*):void;
    public native function writeBytes(bytes:ByteArray, offset:uint = 0, length:uint = 0):void;
    public native function writeMultiByte(value:String, charSet:String):void;
    public native function writeUTF(value:String):void;
    public native function writeUTFBytes(value:String):void;

    public native function get bytesAvailable():uint;
    public native function get position():Number;
  }
}
