// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/StorageVolumeInfo.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.filesystem
{
  import flash.events.EventDispatcher;
  import flash.filesystem.StorageVolume;
  import __ruffle__.stub_method;
  import __ruffle__.stub_getter;
  import __ruffle__.stub_setter;

  [API("668")]
  public final class StorageVolumeInfo extends EventDispatcher
  {

    // The isSupported property is set to true if the StorageVolumeInfo class is supported on the current platform, otherwise it is set to false.
    private var _isSupported:Boolean;

    // The singleton instance of the StorageVolumeInfo object.
    private var _storageVolumeInfo:StorageVolumeInfo;

    // Returns vector of StorageVolume objects corresponding to the currently mounted storage volumes.
    public function getStorageVolumes():Vector.<StorageVolume>
    {
      // Unknown Implementation
      stub_method("flash.filesystem.StorageVolumeInfo", "getStorageVolumes");
    }

    public function get isSupported():Boolean
    {
      stub_getter("flash.filesystem.StorageVolumeInfo", "isSupported");
      return this._isSupported;
    }

    public function get storageVolumeInfo():StorageVolumeInfo
    {
      stub_getter("flash.filesystem.StorageVolumeInfo", "storageVolumeInfo");
      return this._storageVolumeInfo;
    }

  }
}
