// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filesystem/StorageVolume.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.filesystem
{

    import flash.filesystem.File;
    import __ruffle__.stub_method;
    import __ruffle__.stub_getter;
    import __ruffle__.stub_setter;

    public class StorageVolume
    {

        // A File object corresponding to the root directory of the volume.
        private var _rootDirectory:File;

        // The name of the volume.
        private var _name:String;

        // Whether a volume is writable (true) or not (false).
        private var _isWritable:Boolean;

        // The type of file system on the storage volume (such as "FAT", "NTFS", "HFS", or "UFS").
        private var _fileSystemType:String;

        // The volume drive letter on Windows.
        private var _drive:String;

        public function StorageVolume(rootDirPath:File, name:String, writable:Boolean, removable:Boolean, fileSysType:String, drive:String)
        {
            this._rootDirectory = rootDirPath;
            this._name = name;
            this._isWritable = writable;
            this._fileSystemType = fileSysType;
            this._drive = drive;
        }

        public function get rootDirectory():File
        {
            return this._rootDirectory;
        }

        public function get name():String
        {
            return this._name;
        }

        public function get isWritable():Boolean
        {
            return this._isWritable;
        }

        public function get fileSystemType():String
        {
            return this._fileSystemType;
        }

        public function get drive():String
        {
            return this._drive;
        }

    }
}
